import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

export const Colors = {
  mainColor: '#4686D4',
  background: '#ffffff',
  buttoncolor: '#4686D4',
  lightbutton: '#005155',
  black: '#000000',
  lightblack: '#475569',
  inputColor: '#f3f9ff',
  white: '#FFFFFF',
  red: '#FF4B26',
  green: '#00AA38',
  lightgrey: '#D2E0FF',
  boardingColor: '#F1F1F1',
  lightblue: '#0052B4',
  placeholder: '#C9C9C9',
  darkblue: '#101835',
  lightblue: '#6074BC',
  grey: '#E3E3E7',
  lightgrey: '#7D7F88',
};

const fonts = {
  bold: 'Helvetica-Bold',
  medium: 'Helvetica',
  light: 'helvetica-light-587ebe5a59211',

  // Blackfont: 'Nunito-Black',
  // BlackItalic: 'Nunito-BlackItalic',
  // Extrabold: 'Nunito-ExtraBold',
  // boldItalic: 'Nunito-BoldItalic',
  // boldExtraItalic: 'Nunito-ExtraBoldItalic',
  // semibold: 'Nunito-SemiBold',
  // regular: 'Nunito-Regular',
  // lightItalic: 'Nunito-LightItalic',
};
const images = {
  splash: require('../assets/splash.png'),
  logopic: require('../assets/logo.png'),
  riderpic: require('../assets/riderpic.png'),
  driverpic: require('../assets/driverpic.png'),
  onboardpic1: require('../assets/onboardpic1.png'),
  onboardpic2: require('../assets/onboardpic2.png'),
  onboardingD2: require('../assets/onboardingD2.png'),
  onboardingD3: require('../assets/onboardingD3.png'),
  onboardingD4: require('../assets/onboardingD4.png'),

  onboardpicnew2: require('../assets/onboardpicnew2.png'),
  onboardpicnew3: require('../assets/onboardpicnew3.png'),

  onboardpic3: require('../assets/onboardpic3.png'),
  countpic1: require('../assets/countpic1.png'),
  countpic2: require('../assets/countpic2.png'),
  countpic3: require('../assets/countpic3.png'),
  countpicnew3: require('../assets/countpicnew3.png'),
  customerpic: require('../assets/customerpic.png'),

  startedpic: require('../assets/startedpic.png'),
  LocationIcon: require('../assets/LocationIcon.png'),
  welcomepic: require('../assets/welcomepic.png'),
  cityIcon: require('../assets/cityIcon.png'),
  stateIcon: require('../assets/stateIcon.png'),
  postalcodeIcon: require('../assets/postalcodeIcon.png'),
  ibanIcon: require('../assets/ibanIcon.png'),

  avatar: require('../assets/avatar.png'),
  chatpic1: require('../assets/chatpic1.png'),
  chatpic2: require('../assets/chatpic2.png'),
  chatpic3: require('../assets/chatpic3.png'),
  chatpic4: require('../assets/chatpic4.png'),
  chatpic5: require('../assets/chatpic5.png'),
  chatpic6: require('../assets/chatpic6.png'),
  changepasImg: require('../assets/changepasImg.png'),
  walletPic: require('../assets/walletPic.png'),
  graphpic: require('../assets/graphpic.png'),
  transactionIcon: require('../assets/transactionIcon.png'),
  viewfill: require('../assets/viewfill.png'),
  viewunfill: require('../assets/viewunfill.png'),
  bankcardImg: require('../assets/bankcardImg.png'),
  mapBackground: require('../assets/mapBackground.png'),
  carImg: require('../assets/carImg.png'),
  carImg2: require('../assets/carImg2.png'),
  backlayer: require('../assets/backlayer.png'),
  switchtoImg: require('../assets/switchtoImg.png'),
  signoutImg: require('../assets/signoutImg.png'),
  sharewithfriends: require('../assets/sharewithfriends.png'),
  acceptrequestImg: require('../assets/acceptrequestImg.png'),
  reachedbackground: require('../assets/reachedbackground.png'),
  paybackground: require('../assets/paybackground.png'),
  stripebackground: require('../assets/stripebackground.png'),
  paynowImg: require('../assets/paynowImg.png'),
  feedbackImg: require('../assets/feedbackImg.png'),
  offerpricebg: require('../assets/offerpricebg.png'),

  paymentbg: require('../assets/paymentbg.png'),
  termsImg: require('../assets/termsImg.png'),
  privacyImg: require('../assets/privacyImg.png'),
  emergencyGroup: require('../assets/emergencyGroup.png'),

  vehicleImg: require('../assets/vehicleImg.jpg'),
  vehicle2Img: require('../assets/vehicle2Img.png'),
  regImg: require('../assets/regImg.jpg'),
  licenseImg: require('../assets/licenseImg.jpg'),
  numberplateImg: require('../assets/numberplateImg.jpg'),
  driverLngImg: require('../assets/driverLngImg.png'),

  // <-- Icon  Start-->
  plate: require('../assets/plate.png'),

  gmailIcon: require('../assets/gmailIcon.png'),
  dbirthIcon: require('../assets/dbirthIcon.png'),
  usernameIcon: require('../assets/usernameIcon.png'),
  addressIcon: require('../assets/addressIcon.png'),
  facebookicon: require('../assets/facebookicon.png'),
  passkey: require('../assets/passkey.png'),
  locationpic: require('../assets/locationpic.png'),
  studentIcon: require('../assets/studentIcon.png'),

  wearning: require('../assets/wearning.png'),
  profileIcon: require('../assets/profileIcon.png'),
  notifyIcon: require('../assets/notifyIcon.png'),
  chatIcon: require('../assets/chatIcon.png'),
  infoIcon: require('../assets/info.png'),
  menuIcon: require('../assets/menuIcon.png'),
  mapcar: require('../assets/mapcar.png'),
  PlaceInicator: require('../assets/PlaceInicator.png'),
  norides: require('../assets/norides.png'),

  pickupIcon: require('../assets/pickupIcon.png'),
  dropoffIcon: require('../assets/dropoffIcon.png'),
  PolygonIcon: require('../assets/PolygonIcon.png'),
  seatIcon: require('../assets/seatIcon.png'),
  locIcon: require('../assets/locIcon.png'),

  emailIcon: require('../assets/emailIcon.png'),
  usernumIcon: require('../assets/usernumIcon.png'),
  priceIcon: require('../assets/priceIcon.png'),
  rightarrow: require('../assets/rightarrow.png'),
  starImg: require('../assets/starImg.png'),
  uploadIcon: require('../assets/uploadIcon.png'),
  EngyIcon: require('../assets/EngyIcon.png'),

  emergIcon: require('../assets/emergIcon.jpeg'),

  sedanIcon: require('../assets/sedanIcon.png'),
  vehiclemakeIcon: require('../assets/vehiclemakeIcon.png'),
  callicon: require('../assets/callicon.png'),

  licenseplateIcon: require('../assets/licenseplateIcon.png'),
  uploadTag: require('../assets/uploadTag.png'),
  tripImg: require('../assets/tripImg.png'),

  sheetcommentIcon: require('../assets/sheetcommentIcon.png'),
  sheetpass: require('../assets/sheetpass.png'),
  sheetpayment: require('../assets/sheetpayment.png'),
  sheetTimeIcon: require('../assets/sheetTimeIcon.png'),
  paymentImg: require('../assets/paymentImg.png'),
  bmenuIcon: require('../assets/bmenuIcon.png'),

  incoming: require('../assets/incoming.png'),
  acceptImg: require('../assets/acceptImg.png'),
  completeImg: require('../assets/completeImg.png'),

  arrowRight: require('../assets/arrowRight.png'),
  arrowLeft: require('../assets/arrowLeft.png'),
  arrowBack: require('../assets/arrowBack.png'),
  arrowStright: require('../assets/arrowStright.png'),

  // <--End Icon --/>
};
export {fonts, images};

export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    // backgroundColor: Colors.background,
  },
  selectionView: {
    width: wp(35),
    height: wp(35),
    borderRadius: wp(4),
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowOffset: {height: 2, width: 2},
    shadowOpacity: 0.2,
    shadowColor: '#4686D4',
    marginBottom: wp(2),
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  imgStyle: {
    width: wp(33),
    height: wp(33),
  },
  btnView: {
    width: wp(90),
    height: wp(13),
    borderRadius: wp(2),
    backgroundColor: Colors.buttoncolor,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },

  selectionText: {
    fontSize: 14,
    fontFamily: fonts.bold,
    color: '#2D3D54',
  },
  checkboxstyle: {
    position: 'absolute',
    width: wp(7),
    height: wp(7),
    borderRadius: wp(4),
    backgroundColor: Colors.buttoncolor,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-end',
    top: wp(0),
  },
  HeaderView: {
    width: wp(100),
    justifyContent: 'center',
    // flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    height: wp(20),
    backgroundColor: Colors.background,
    // borderBottomLeftRadius: wp(8),
    // borderBottomRightRadius: wp(8),
    elevation: 2,
    marginBottom: wp(0.5),
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  arrowStyle: {
    position: 'absolute',
    left: wp(5),
    top: wp(7),
  },
  headerText: {
    fontSize: 16,
    fontFamily: fonts.bold,
    color: Colors.black,
    textAlign: 'center',
  },
  listContainer: {
    paddingBottom: 24,
  },
  vehicleOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: wp(4),
    marginVertical: wp(2.5),
    elevation: 2,
    width: wp(90),
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  selectedOption: {
    borderWidth: 1.5,
    borderColor: Colors.buttoncolor,
  },
  vehicleText: {
    fontSize: 14,
    fontWeight: '500',
    color: 'black',
  },
  radioButton: {
    width: 17,
    height: 17,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.black,
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioSelected: {
    width: 11,
    height: 11,
    borderRadius: 7,
    backgroundColor: Colors.buttoncolor,
  },
  continueButton: {
    backgroundColor: '#1B8DFF',
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
    marginVertical: 16,
  },
  disabledButton: {
    backgroundColor: '#A9CCE3',
  },
  continueText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 16,
  },
  onboardingImgView: {
    width: wp(90),
    height: wp(80),
    alignSelf: 'center',
  },
  onboardTextH: {
    fontSize: 16,
    color: Colors.black,
    fontFamily: fonts.bold,
    textAlign: 'center',
    marginBottom: wp(3),
  },
  onboardTextP: {
    fontSize: 14,
    color: '#A0A0A0',
    fontFamily: fonts.medium,
    textAlign: 'center',
    lineHeight: 22,
  },
  boardingtextView: {
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: wp(15),
  },
  countStyle: {
    width: wp(20),
    height: wp(20),
  },
  btn2View: {
    width: wp(90),
    height: wp(13),
    borderRadius: wp(2),
    backgroundColor: Colors.background,
    borderWidth: 1,
    borderColor: Colors.buttoncolor,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  title2Text: {
    fontSize: 16,
    fontFamily: fonts.bold,
    color: Colors.buttoncolor,
  },
  inputViewStyle: {
    width: wp(90),
    height: wp(13),
    borderRadius: wp(7),
    backgroundColor: Colors.inputColor,
    alignSelf: 'center',
    paddingLeft: wp(5),
    flexDirection: 'row',
    alignItems: 'center',
    elevation: 2,
    borderColor: Colors.buttoncolor,
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  inputStyle: {
    width: wp(75),
    height: wp(12),
    backgroundColor: Colors.inputColor,
    borderRadius: wp(2),
    marginLeft: 3,
    alignSelf: 'center',
    color: Colors.black,
  },
  inputView: {
    width: wp(90),
    alignSelf: 'center',
    marginTop: wp(3),
  },
  labelStyle: {
    fontSize: 12,
    color: Colors.black,
    fontFamily: fonts.bold,
    paddingLeft: wp(1),
    marginBottom: wp(1),
  },
  searchViewStyle: {
    width: wp(90),
    height: wp(13),
    borderRadius: wp(2),
    backgroundColor: Colors.inputColor,
    alignSelf: 'center',
    paddingHorizontal: wp(4),
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkrow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: wp(5),
    marginTop: wp(2),
    justifyContent: 'space-between',
  },
  bottomView: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: wp(7),
    // marginBottom: wp(5),
  },
  bottomText: {
    fontSize: 12,
    fontFamily: fonts.medium,
    color: Colors.black,
  },
  facebookbutton: {
    width: wp(90),
    height: wp(13),
    borderRadius: wp(2),
    backgroundColor: '#4460A0',
    // borderWidth: 1,
    borderColor: '#4460A0',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: wp(4),
    marginBottom: wp(4),
  },
  titleText: {
    fontSize: 14,
    fontFamily: fonts.bold,
    color: Colors.white,
  },
  profileStyle: {
    width: wp(22),
    height: wp(22),
    borderRadius: wp(11),
    alignSelf: 'center',
  },
  container: {
    marginBottom: 20,
  },
  label: {
    fontSize: 14,
    fontFamily: fonts.medium,
    color: Colors.black,
  },
  inputRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: wp(90),
    alignSelf: 'center',
  },
  input: {
    flex: 1,
    height: wp(13),
    marginRight: 8,
    borderWidth: 1,
    borderColor: Colors.buttoncolor,
    borderRadius: 25,
    textAlign: 'center',
    backgroundColor: Colors.inputColor,
    fontSize: 14,
    fontFamily: fonts.medium,
    color: Colors.black,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  inputLong: {
    flex: 2,
    borderWidth: 1,
    height: wp(13),
    borderColor: Colors.buttoncolor,
    borderRadius: 25,
    textAlign: 'center',
    backgroundColor: Colors.inputColor,
    fontSize: 14,
    fontFamily: fonts.medium,
    color: Colors.black,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  pinView: {
    alignItems: 'center',
    alignSelf: 'center',
    width: wp(80),
    marginTop: wp(25),
    height: wp(18),
  },
  cell: {
    width: wp(14),
    height: hp(7),
    lineHeight: wp(14),
    fontSize: 20,
    fontFamily: fonts.regular,
    borderRadius: wp(10),
    backgroundColor: Colors.white,
    textAlign: 'center',
    marginHorizontal: wp(4),
    color: Colors.black,
    elevation: 2,
    borderWidth: 1,
    borderColor: Colors.buttoncolor,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  counter: {
    alignSelf: 'center',
    // right: wp(5),
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: wp(2),
  },

  idText: {
    fontSize: 11,
    fontFamily: fonts.regular,
    color: Colors.white,
  },
  counter_txt: {
    color: Colors.black,
    fontFamily: fonts.bold,
    fontSize: 14,
    textDecorationLine: 'underline',
  },
  counterContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    // marginTop: wp(5),
    marginHorizontal: wp(7),
  },
  resendPrompt: {
    fontSize: 12,
    color: Colors.black,
    fontFamily: fonts.medium,
    // marginLeft: wp(13),
  },
  containerbottom: {
    flex: 1,
    padding: 20,
  },
  shawdow: {
    shadowColor: '#DDDDDD',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 1,
    shadowRadius: 5,
  },
  button: {
    justifyContent: 'center',
    borderRadius: 15,
    // borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  bottomBar: {},
  btnCircleUp: {
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.buttoncolor,
    bottom: 25,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  imgCircle: {
    width: 30,
    height: 30,
    tintColor: '#9E9E9E',
  },
  tabbarItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  img: {
    width: 30,
    height: 30,
  },

  MemIconimg: {
    width: 200,
    height: 200,
  },
  noficationView: {
    width: wp(90),
    borderRadius: wp(2),
    backgroundColor: Colors.white,
    marginBottom: wp(3),
    elevation: 2,
    paddingHorizontal: wp(3),
    paddingVertical: wp(3),
    alignSelf: 'center',
    marginTop: wp(1),
    shadowOffset: {height: 2, width: 2},
    shadowOpacity: 0.2,
    shadowColor: '#4686D4',
  },
  notiHeading: {
    fontSize: 12,
    fontFamily: fonts.bold,
    color: Colors.black,
    marginLeft: wp(2),
  },
  notiTExt: {
    fontSize: 12,
    color: '#666666',
    fontFamily: fonts.medium,
  },
  messagesView: {
    width: wp(90),
    marginBottom: wp(2),
    // elevation: 2,
    paddingHorizontal: wp(3),
    paddingVertical: wp(3),
    alignSelf: 'center',
    marginTop: wp(1),
    borderBottomWidth: 1,
    borderColor: '#E5E5E5',
  },
  flattoptext: {
    fontSize: 12,
    fontFamily: fonts.bold,
    color: Colors.black,
  },
  chatdic: {
    fontSize: 12,
    fontFamily: fonts.regular,
    color: Colors.lightblack,
    // backgroundColor: 'red',
    maxWidth: wp(60),
  },
  bottomHeaderView: {
    width: wp(100),
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    height: wp(20),

    backgroundColor: 'white',

    // borderBottomLeftRadius: wp(8),
    // borderBottomRightRadius: wp(8),
    marginBottom: wp(1),
    // elevation: 2,
    // opacity:0.7
  },
  walletTopView: {
    width: wp(90),
    borderRadius: wp(2),
    backgroundColor: Colors.white,
    marginBottom: wp(3),
    elevation: 2,
    paddingHorizontal: wp(5),
    paddingVertical: wp(3),
    alignSelf: 'center',
    marginTop: wp(3),
    shadowOffset: {height: 2, width: 2},
    shadowOpacity: 0.2,
    shadowColor: '#4686D4',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  paymentStyle: {
    fontSize: 16,
    fontFamily: fonts.bold,
    color: Colors.buttoncolor,
  },
  graphView: {
    width: wp(90),
    borderRadius: wp(2),
    backgroundColor: Colors.white,
    marginBottom: wp(3),
    elevation: 2,
    paddingHorizontal: wp(5),
    paddingVertical: wp(3),
    alignSelf: 'center',
    marginTop: wp(3),
    shadowOffset: {height: 2, width: 2},
    shadowOpacity: 0.2,
    shadowColor: '#4686D4',
    justifyContent: 'center',
    alignItems: 'center',
  },
  transactionView: {
    width: wp(90),
    borderRadius: wp(2),
    backgroundColor: Colors.white,
    marginBottom: wp(3),
    elevation: 2,
    paddingHorizontal: wp(3),
    paddingVertical: wp(3),
    alignSelf: 'center',
    marginTop: wp(1),
    shadowOffset: {height: 2, width: 2},
    shadowOpacity: 0.2,
    shadowColor: '#4686D4',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  PickupView: {
    width: wp(90),
    // flex:1,
    borderRadius: wp(4),
    backgroundColor: Colors.white,
    // marginBottom: wp(3),
    elevation: 2,
    paddingHorizontal: wp(3),
    paddingVertical: wp(3),
    alignSelf: 'center',
    marginTop: wp(1),
    shadowOffset: {height: 2, width: 2},
    shadowOpacity: 0.2,
    shadowColor: '#4686D4',
    justifyContent: 'space-between',
  },
  priceView: {
    width: wp(17),
    borderRadius: wp(4),
    backgroundColor: Colors.white,
    // marginBottom: wp(3),
    elevation: 2,
    paddingHorizontal: wp(3),
    paddingVertical: wp(4),
    alignSelf: 'center',
    marginTop: wp(1),
    shadowOffset: {height: 2, width: 2},
    shadowOpacity: 0.2,
    shadowColor: '#4686D4',
    justifyContent: 'center',
    alignItems: 'center',
  },
  priceView2: {
    width: wp(30),
    borderRadius: wp(4),
    backgroundColor: Colors.white,
    // marginBottom: wp(3),
    elevation: 2,
    paddingHorizontal: wp(3),
    paddingVertical: wp(8),
    alignSelf: 'center',
    marginTop: wp(1),
    shadowOffset: {height: 2, width: 2},
    shadowOpacity: 0.2,
    shadowColor: '#4686D4',
    justifyContent: 'center',
    alignItems: 'center',
  },
  priceInnerView: {
    width: wp(7),
    height: wp(7),
    borderRadius: wp(2),
    backgroundColor: Colors.buttoncolor,
    justifyContent: 'center',
    alignItems: 'center',
  },
  topvehicleView: {
    paddingHorizontal: wp(4),
    paddingVertical: wp(4),
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: wp(80),
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 20,
  },
  itemContainer: {
    paddingVertical: 5,
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
  },
  itemText: {
    fontSize: 16,
    textAlign: 'center',
    color: Colors.black,
  },
  closeButton: {
    backgroundColor: '#FF2438',
    padding: 10,
    borderRadius: 5,
    marginTop: 10,
  },
  closeButtonText: {
    color: '#fff',
    textAlign: 'center',
    fontSize: 16,
  },
  utitityMainView: {
    width: wp(100),
    backgroundColor: '#FFFFFF',
    // height:wp(80),
    borderTopLeftRadius: wp(4),
    borderTopRightRadius: wp(4),
    paddingHorizontal: wp(4),
    paddingVertical: wp(4),
    bottom: wp(0),
    position: 'absolute',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
  },
  utilitysectionView: {
    width: wp(90),
    borderRadius: wp(2),
    backgroundColor: Colors.white,
    marginBottom: wp(3),
    elevation: 2,
    paddingHorizontal: wp(3),
    paddingVertical: wp(3),
    alignSelf: 'center',
    marginTop: wp(1),
    shadowOffset: {height: 2, width: 2},
    shadowOpacity: 0.2,
    shadowColor: '#4686D4',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  utilityText: {
    fontSize: 13,
    fontFamily: fonts.medium,
    color: Colors.black,
    lineHeight: 22,
  },
  RideStyleView: {
    width: wp(90),
    borderRadius: wp(2),
    backgroundColor: Colors.white,
    marginBottom: wp(4),
    elevation: 2,
    paddingHorizontal: wp(3),
    paddingVertical: wp(3),
    alignSelf: 'center',
    marginTop: wp(1),
    shadowOffset: {height: 2, width: 2},
    shadowOpacity: 0.2,
    shadowColor: '#4686D4',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  tabStyleView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: wp(30),
    borderBottomWidth: 1,
    borderColor: '#E5E5E5',
    paddingBottom: wp(3),
  },
  DriverView: {
    width: wp(90),
    borderRadius: wp(2),
    backgroundColor: Colors.white,
    marginBottom: wp(4),
    elevation: 2,
    paddingHorizontal: wp(3),
    paddingVertical: wp(3),
    alignSelf: 'center',
    marginTop: wp(1),
    shadowOffset: {height: 2, width: 2},
    shadowOpacity: 0.2,
    shadowColor: '#4686D4',
  },
  driverimg: {
    width: wp(10),
    height: wp(10),
    borderRadius: wp(5),
  },
  usernameText: {
    fontSize: 14,
    fontFamily: fonts.bold,
    color: Colors.black,
  },
  line: {
    width: 200,
    height: wp(0.3),
    backgroundColor: '#DFDFDF',
    alignSelf: 'center',
    borderRadius: 30,
    opacity: 0.6,
  },
  row: {
    width: 180,
    height: wp(14),
    backgroundColor: Colors.buttoncolor,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    bottom: 0,
    marginTop: wp(4),
    flex: 1,
  },
  screenname: {
    fontSize: 14,
    color: Colors.black,
    marginLeft: wp(3),
    fontFamily: fonts.bold,
    // marginTop: wp(1),
  },
  infoStyle: {
    fontSize: 14,
    fontFamily: fonts.bold,
    color: Colors.lightblack,
    textAlign: 'center',
    marginBottom: wp(2),
  },
  contactItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 10,
    marginBottom: wp(3),
    width: wp(90),
    alignSelf: 'center',
    height: wp(14),
    shadowOffset: {height: 2, width: 2},
    shadowOpacity: 0.2,
    shadowColor: '#4686D4',
    elevation: 2,
    backgroundColor: 'white',
    paddingHorizontal: wp(3),
    marginTop: wp(1),
  },
  selectedContact: {
    backgroundColor: '#E0F7FA',
    borderColor: '#40A1FF',
  },
  contactName: {
    fontSize: 14,
    fontWeight: Colors.medium,
    color: Colors.black,
  },
  contactPhone: {
    fontSize: 13,
    color: Colors.buttoncolor,
    fontFamily: fonts.medium,
  },
  checkmark: {
    fontSize: 20,
    color: '#40A1FF',
    fontWeight: 'bold',
  },
  addButton: {
    backgroundColor: '#40A1FF',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 20,
  },
  addButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  modalTopView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalsecondView: {
    width: wp(90),
    // height: wp(60),
    borderRadius: wp(4),
    // justifyContent: 'space-between',
    backgroundColor: Colors.background,
    paddingVertical: wp(10),
  },
  modalText: {
    fontSize: 16,
    fontFamily: fonts.bold,
    color: Colors.black,
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: wp(1),
  },
  modalbutton1: {
    width: wp(33),
    height: wp(12),
    backgroundColor: Colors.buttoncolor,
    borderRadius: wp(3),
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalbutton2: {
    width: wp(33),
    height: wp(12),
    backgroundColor: Colors.white,
    borderRadius: wp(3),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#D63544',
  },
  chatList: {
    flexGrow: 1,
    justifyContent: 'flex-end',
  },
  chatView: {
    // width: wp(50),
    maxWidth: wp(75),
    borderTopLeftRadius: wp(3),
    borderBottomLeftRadius: wp(3),
    borderTopRightRadius: wp(3),
    backgroundColor: Colors.buttoncolor,
    padding: wp(3),
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: wp(3),
  },
  messageContainer: {
    flexDirection: 'row',
    // alignItems: 'flex-end',
    marginVertical: 5,
    marginHorizontal: 10,
    paddingVertical: wp(2),
    maxWidth: wp(75),
  },
  myMessage: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignSelf: 'flex-end',
    paddingVertical: wp(2),
    alignItems: 'center',
  },
  myMessagereceive: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignSelf: 'flex-start',
    paddingVertical: wp(2),
    alignItems: 'center',
  },
  avatar: {
    width: 30,
    height: 30,
    borderRadius: 15,
    marginRight: 8,
  },
  messageBubble: {
    padding: 10,
    // maxWidth: '90%',
    // borderTopLeftRadius: wp(3),
  },
  userBubble: {
    backgroundColor: '#C6DEFB',
    borderTopRightRadius: wp(3),
    borderBottomLeftRadius: wp(3),
    borderBottomRightRadius: wp(3),
    maxWidth: '75%',
    padding: 10,
  },
  myBubble: {
    backgroundColor: Colors.buttoncolor,
    borderTopLeftRadius: wp(3),
    borderBottomLeftRadius: wp(3),
    borderBottomRightRadius: wp(3),
    padding: 10,

    maxWidth: '75%',
    // width:wp(90)
  },
  messageText: {
    color: '#000',
  },
  messageTime: {
    fontSize: 10,
    color: '#888',
    marginHorizontal: 5,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderTopWidth: 1,
    borderTopColor: '#ddd',
  },
  inputtext: {
    paddingVertical: 8,
    paddingHorizontal: 15,
    marginRight: 10,
    width: wp(70),
    fontSize: 14,
    color: Colors.black,
  },
  sendButton: {
    backgroundColor: '#3A7BD5',
    borderRadius: 20,
    padding: 7,
  },
  sendText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  rowContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    // marginHorizontal:wp(5),
    marginTop: wp(1),
  },
  uploadBox: {
    width: wp(43),
    height: wp(20),
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: Colors.buttoncolor,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: wp(2),
  },
  uploadBoxFull: {
    width: wp(100),
    height: wp(20),
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: Colors.buttoncolor,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: wp(2),
  },
  uploadText: {
    marginLeft: wp(2),
    color: '#888',
    fontSize: 12,
  },
  uploadBox2: {
    width: wp(90),
    height: wp(20),
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: Colors.buttoncolor,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: wp(2),
  },
  uploadBoxFull: {
    width: wp(100),
    height: wp(20),
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: Colors.buttoncolor,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: wp(2),
  },
  dropdown: {
    borderWidth: 1,
    borderColor: Colors.buttoncolor,
    borderRadius: wp(8),
    padding: 12,
    // marginBottom: 16,
    fontSize: 12,
    color: Colors.black,
    backgroundColor: Colors.inputColor,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  dropdownHome: {
    width: wp(90),
    borderRadius: wp(3),
    backgroundColor: Colors.white,
    // marginBottom: wp(3),
    elevation: 2,
    paddingHorizontal: wp(4),
    paddingVertical: wp(3),
    alignSelf: 'center',
    marginTop: wp(1),
    shadowOffset: {height: 2, width: 2},
    shadowOpacity: 0.2,
    shadowColor: '#4686D4',
    justifyContent: 'space-between',
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    // justifyContent: 'center',
    // alignItems: 'center',
  },
  closeButton: {
    position: 'absolute',
    top: 20,
    right: 20,
    zIndex: 1,
  },
  fullImage: {
    width: wp(100),
    flex: 1,
    // height: hp(40),
    // borderRadius: 10,
  },
  phoneContainerStyle: {
    width: wp(84),
    alignSelf: 'center',
    height: wp(12),
    borderRadius: wp(8),
    backgroundColor: Colors.inputColor,
  },
  phonetextContainer: {
    width: wp(90),
    color: 'black',
    height: wp(12),
    borderRadius: wp(8),
    backgroundColor: Colors.inputColor,
    alignItems: 'center',
    // backgroundColor:'red',
    marginLeft: wp(-2),
  },
  errortxt: {
    fontSize: 10,
    color: 'red',
    fontFamily: fonts.medium,
    marginLeft: wp(3),
    marginRight: wp(5),
  },
  imageerr: {
    fontSize: 10,
    color: 'red',
    fontFamily: fonts.medium,
    textAlign: 'center',
    marginTop: wp(2),
  },
  chattime: {
    fontSize: 10,
    color: Colors.lightblack,
    fontFamily: fonts.medium,
  },
  chatmessages: {
    fontSize: 14,
    color: Colors.white,
    fontFamily: fonts.medium,
  },
  modalContainerPro: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
  },
  modalContentPro: {
    width: wp(80),
    backgroundColor: Colors.white,
    borderRadius: wp(3),
    padding: wp(10),
    alignItems: 'center',
  },
  modalTextPro: {
    fontSize: wp(4),
    color: Colors.black,
    fontFamily: fonts.medium,
    textAlign: 'center',
    marginBottom: wp(5),
  },
  modalButtonPro: {
    width: wp(40),
    height: wp(10),
    borderRadius: wp(2),
    backgroundColor: Colors.buttoncolor,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalButtonText: {
    fontSize: wp(4),
    color: Colors.white,
    fontFamily: fonts.medium,
  },
  codeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: wp(90),
    height: 48,
    backgroundColor: '#F5F9FF',
    borderRadius: 50,
    borderWidth: 1,
    borderColor: '#4686D4',
    // padding: 10,
    paddingHorizontal: 20,
    marginBottom: 20,
    alignSelf: 'center',
  },
  codeInput: {
    width: 30,
    height: 42,
    // backgroundColor:'red',
    borderBottomWidth: 1.23,
    borderColor: '#4686D4',
    fontSize: 18,
    textAlign: 'center',
    color: Colors.black,
  },
  subtitle: {
    fontSize: 12,
    // marginVertical: 20,
    marginBottom: 20,
    textAlign: 'center',
    color: '#000000',
    fontFamily: fonts.medium,
  },
  markerIcon: {
    width: 30,
    height: 30,
    resizeMode: 'contain',
  },
  carIcon: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
  },
  startButton: {
    position: 'absolute',
    bottom: 30,
    left: '20%',
    right: '20%',
    backgroundColor: '#1B8DFF',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
  },
  buttonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  infoContainer: {
    position: 'absolute',
    top: wp(90),
    left: '10%',
    right: '30%',
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    padding: 10,
    borderRadius: 10,
    alignItems: 'center',
  },
  infoText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#000',
  },
  bottomSheetTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 20,
    color: 'black',
  },
  payButton: {
    backgroundColor: '#1B8DFF',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
  },
  payButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  dropdownOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
  },
  dropdownContainer: {
    marginTop: wp(12),
    marginRight: wp(4),
    backgroundColor: Colors.white,
    borderRadius: wp(2),
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  dropdownItem: {
    padding: wp(6),
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    marginBottom: wp(1),
  },
  dropdownText: {
    fontSize: 14,
    fontFamily: fonts.medium,
    color: Colors.black,
  },
  // contactItem: {
  //   flexDirection: 'row',
  //   justifyContent: 'space-between',
  //   alignItems: 'center',
  //   padding: wp(3),
  //   borderBottomWidth: 1,
  //   borderBottomColor: Colors.gray,
  //   marginHorizontal: wp(2.8),
  // },
  // contactName: {
  //   fontSize: 16,
  //   fontFamily: fonts.regular,
  //   color: Colors.black,
  // },
  // contactPhone: {
  //   fontSize: 14,
  //   fontFamily: fonts.regular,
  //   color: Colors.gray,
  // },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  noContacts: {
    fontSize: 16,
    fontFamily: fonts.regular,
    color: Colors.gray,
    textAlign: 'center',
    marginTop: wp(5),
  },
  list: {
    flex: 1,
  },

  adText: {
    color: '#666',
    fontSize: 14,
    fontFamily: fonts.bold,
  },
  adContainer: {
    width: wp(90),
    alignSelf: 'center',
    height: wp(16),
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: 'white',
    elevation: 2,
    shadowColor: 'black',
    shadowOffset: {width: 1, height: 1},
    shadowOpacity: 0.14,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: wp(1),
  },
  sheetButton: {
    width: wp(90),
    backgroundColor: '#fff',
    elevation: 4,
    padding: wp(5),
    borderRadius: wp(4),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: wp(3),
    alignSelf: 'center',
  },
  sheetText: {
    fontSize: 13,
    fontFamily: fonts.medium,
    color: Colors.black,
  },
});
